export type Product = {
  id: string
  name: string
  category: "Ice Cream" | "Boba Tea" | "Pastries" | "Pancakes"
  price: number
  description: string
  flavors: string[]
  popularity: number
  image: string
}

export const products: Product[] = [
  // Ice Cream
  {
    id: "1",
    name: "Vanilla Bean Ice Cream",
    category: "Ice Cream",
    price: 15.0,
    description: "Classic vanilla ice cream made with real Madagascar vanilla beans",
    flavors: ["Vanilla"],
    popularity: 95,
    image: "/images/vanilla.png",
  },
  {
    id: "2",
    name: "Chocolate Fudge Ice Cream",
    category: "Ice Cream",
    price: 18.0,
    description: "Rich chocolate ice cream with fudge swirls",
    flavors: ["Chocolate"],
    popularity: 92,
    image: "/chocolate-ice-cream-scoop.png",
  },
  {
    id: "3",
    name: "Strawberry Delight Ice Cream",
    category: "Ice Cream",
    price: 16.0,
    description: "Fresh strawberry ice cream with real fruit pieces",
    flavors: ["Strawberry"],
    popularity: 88,
    image: "/strawberry-ice-cream-scoop.png",
  },
  {
    id: "4",
    name: "Mint Chocolate Chip Ice Cream",
    category: "Ice Cream",
    price: 17.0,
    description: "Refreshing mint ice cream with chocolate chips",
    flavors: ["Mint"],
    popularity: 85,
    image: "/mint-chocolate-chip-ice-cream.jpg",
  },
  // Boba Tea
  {
    id: "5",
    name: "Classic Milk Tea",
    category: "Boba Tea",
    price: 20.0,
    description: "Traditional milk tea with chewy tapioca pearls",
    flavors: ["Original"],
    popularity: 90,
    image: "/milk-tea-boba-drink.jpg",
  },
  {
    id: "6",
    name: "Taro Boba Tea",
    category: "Boba Tea",
    price: 22.0,
    description: "Creamy taro-flavored tea with boba pearls",
    flavors: ["Taro"],
    popularity: 87,
    image: "/taro-boba-tea-purple.jpg",
  },
  {
    id: "7",
    name: "Strawberry Boba Tea",
    category: "Boba Tea",
    price: 21.0,
    description: "Sweet strawberry tea with fresh fruit and boba",
    flavors: ["Strawberry"],
    popularity: 84,
    image: "/strawberry-boba-tea-pink.jpg",
  },
  {
    id: "8",
    name: "Matcha Boba Tea",
    category: "Boba Tea",
    price: 23.0,
    description: "Premium matcha green tea with tapioca pearls",
    flavors: ["Matcha"],
    popularity: 82,
    image: "/matcha-green-tea-boba.jpg",
  },
  // Pastries
  {
    id: "9",
    name: "Chocolate Croissant",
    category: "Pastries",
    price: 12.0,
    description: "Buttery croissant filled with rich chocolate",
    flavors: ["Chocolate"],
    popularity: 91,
    image: "/chocolate-croissant-pastry.jpg",
  },
  {
    id: "10",
    name: "Blueberry Danish",
    category: "Pastries",
    price: 14.0,
    description: "Flaky danish pastry with blueberry filling",
    flavors: ["Blueberry"],
    popularity: 86,
    image: "/blueberry-danish-pastry.jpg",
  },
  {
    id: "11",
    name: "Cinnamon Roll",
    category: "Pastries",
    price: 13.0,
    description: "Soft cinnamon roll with cream cheese frosting",
    flavors: ["Cinnamon"],
    popularity: 89,
    image: "/cinnamon-roll-frosting.jpg",
  },
  {
    id: "12",
    name: "Almond Croissant",
    category: "Pastries",
    price: 15.0,
    description: "Croissant filled with almond cream and topped with sliced almonds",
    flavors: ["Almond"],
    popularity: 83,
    image: "/placeholder.svg?height=400&width=400",
  },
  // Pancakes
  {
    id: "13",
    name: "Classic Buttermilk Pancakes",
    category: "Pancakes",
    price: 25.0,
    description: "Fluffy buttermilk pancakes served with maple syrup",
    flavors: ["Original"],
    popularity: 93,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "14",
    name: "Chocolate Chip Pancakes",
    category: "Pancakes",
    price: 28.0,
    description: "Pancakes loaded with chocolate chips",
    flavors: ["Chocolate"],
    popularity: 90,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "15",
    name: "Blueberry Pancakes",
    category: "Pancakes",
    price: 27.0,
    description: "Pancakes with fresh blueberries",
    flavors: ["Blueberry"],
    popularity: 88,
    image: "/blueberry-pancakes-stack.jpg",
  },
  {
    id: "16",
    name: "Banana Nutella Pancakes",
    category: "Pancakes",
    price: 30.0,
    description: "Pancakes with banana slices and Nutella spread",
    flavors: ["Banana", "Chocolate"],
    popularity: 85,
    image: "/banana-nutella-pancakes.jpg",
  },
]
